menu:
  Home: /
  Archives: /archives

addthis:
  enable: true
  pubid:
  facebook: false
  twitter: false
  google: false
  pinterest: false

facebook:
google_plus:
twitter:
github:

fancybox: true
google_analytics:
rss:
